workflows:
  stores-delivery:
    name: Stores Delivery
    integrations:
      app_store_connect: code_magic
    max_build_duration: 120
    triggering:
      events:
        - tag
      cancel_previous_builds: true
    environment:
      android_signing:
        - default_keystore
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.ldcapps.svr
      groups:
        - default
      vars:
        PACKAGE_NAME: "com.ldcapps.svr"
        GOOGLE_PLAY_TRACK: internal
        BUNDLE_ID: "com.ldcapps.svr"
        # XCODE_WORKSPACE: "CodemagicSample.xcworkspace" # <-- Name of your Xcode workspace
        # XCODE_SCHEME: "CodemagicSample"
        # You may need to set other iOS-related environment variables here.
      flutter: stable
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      # - name: Build AAB with Flutter
      #   script: | 
      #     flutter build appbundle --release
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: | 
          flutter build ipa --release --export-options-plist /Users/builder/export_options.plist 
    artifacts:
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      slack:
        channel: '#svr'
        notify_on_build_start: true
        notify:
          success: true
          failure: true
      email:
        recipients:
          - ldc22@gmail.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true
      app_store_connect:
        auth: integration
