name: svr
description: A new Flutter project.

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #FIREBASE
  firebase_core: ^2.15.0
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.0.15

  #UI
  overlay_support: ^2.0.1
  carousel_slider: ^4.2.1
  syncfusion_flutter_gauges: ^24.1.41
  syncfusion_flutter_charts: ^24.1.41

  #OUTROS
  intl: ^0.18.0
  rxdart: ^0.27.4
  shared_preferences: ^2.0.15
  flutter_native_splash: ^2.2.0+1
  isoweek: ^1.1.4
  easy_localization: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher/launcher.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#F9FAFC"
  image: assets/launcher/splash.png
  android_12:
    image: assets/launcher/splash.png
    icon_background_color: "#F9FAFC"

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/launcher/
    - assets/translations/