name: svr
description: A new Flutter project.

publish_to: 'none'

version: 3.0.0+2

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_mobile_ads: ^2.3.0
  intl: ^0.18.0
  rxdart: ^0.27.4
  flutter_staggered_grid_view: ^0.6.2
  google_fonts: ^4.0.3
  share_plus: ^6.3.1
  url_launcher: ^6.1.5
  flutter_local_notifications: ^9.7.0
  firebase_core: ^2.7.0
  firebase_messaging: ^14.2.5
  firebase_remote_config: ^3.0.13
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  flutter_fgbg: ^0.2.0
  cached_network_image: ^3.2.2
  # facebook_app_events: ^0.18.3
  http: ^0.13.5
  extended_masked_text: ^2.3.1
  firebase_crashlytics: ^3.0.15
  firebase_analytics: ^10.1.4
  flutter_native_splash: ^2.2.18
  # webfeed_plus: ^1.0.0
  html: ^0.15.2
  flutter_launcher_icons: ^0.12.0
  youtube_player_flutter: ^8.1.2
  flutter_svg: ^1.1.6
  flutter_inappwebview: ^5.7.2+3
  material_symbols_icons: ^4.2661.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  android: true
  ios: true
  web: true
  color: "#1C44F9"
  image: assets/launcher/splash.png
  android_12:
    image: assets/launcher/splash.png
    icon_background_color: "#1C44F9"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/launcher/launcher.png"
  image_path_android: "assets/launcher/launcher.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter:

  uses-material-design: true 

  assets:
    - assets/images/
    - assets/launcher/

  fonts:

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900

        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800

        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700

        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500

        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400

        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300

        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200

        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100