# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

pod 'FirebaseAnalytics'
pod 'Google-Mobile-Ads-SDK'
pod 'FirebaseMessaging'
pod 'FirebaseRemoteConfig'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
