name: Auto Tag and Update Gradle Version

on:
  push:
    branches:
      - re_design

jobs:
  tag_and_update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Extract version from pubspec.yaml
        id: get_version
        run: |
          NEW_VERSION=$(grep 'version:' pubspec.yaml | cut -d ' ' -f 2 | cut -d '+' -f 1)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update android/app/build.gradle
        run: |
          FLUTTER_VERSION_CODE=$(echo $NEW_VERSION | awk -F. '{print $1$2$3}')

          # Atualize o versionCode
          sed -i "s/versionCode .*/versionCode $FLUTTER_VERSION_CODE/" android/app/build.gradle
          # Atualize o versionName
          sed -i "s/versionName \".*\"/versionName \"$NEW_VERSION\"/" android/app/build.gradle

          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "paulo@ldcapps.com"
          git add android/app/build.gradle
          git commit -m "release $NEW_VERSION"
          git push

      - name: Create a new tag
        if: env.NEW_VERSION
        run: |
          git tag $NEW_VERSION
          git push origin $NEW_VERSION