name: Release Checker

on:
  push:
    branches:
      - main

jobs:
  release_checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verificando versão
        run: |
          git log -n 2 --pretty=format:"%h" > commits.txt
          commit_array=($(cat commits.txt))

          old_version=$(git show ${commit_array[1]}:pubspec.yaml | grep -o "version: [0-9.]*")
          new_version=$(git show ${commit_array[0]}:pubspec.yaml | grep -o "version: [0-9.]*")

          if [ "$old_version" = "$new_version" ]; then
            echo "A versão do pubspec.yaml não foi alterada. Interrompendo o script."
            exit 0
          else
            echo "A versão do pubspec.yaml mudou de $old_version para $new_version. Continuando o script."
          fi

      - name: Verificando ID's
        run: |
          applicationId=$(grep "applicationId" android/app/build.gradle | awk '{print $2}' | tr -d '"')
          if [ "$applicationId" == "com.ldcapps.svr" ]; then
            echo "Bundle Válido."
          else
            echo "ERRO: Bundle Inválido."
            exit 1
          fi

          facebookAppId=$(grep '<string name="facebook_app_id">' android/app/src/main/res/values/strings.xml | awk -F'>' '{print $2}' | awk -F'<' '{print $1}')
          if [ "$facebookAppId" == "211276778576583" ]; then
            echo "facebook_app_id Válido."
          else
            echo "ERRO: facebook_app_id Inválido."
            exit 1
          fi

          facebookClientToken=$(grep '<string name="facebook_client_token">' android/app/src/main/res/values/strings.xml | awk -F'>' '{print $2}' | awk -F'<' '{print $1}')
          if [ "$facebookClientToken" == "e062eae9839775fd3987551aae1fb0de" ]; then
            echo "facebook_client_token Válido."
          else
            echo "ERRO: facebook_client_token Inválido."
            exit 1
          fi

          if grep -q "KochavaTracker.instance.registerAndroidAppGuid(\"ko-1-svr-qbw\");" lib/app/core/services/log_manager_service.dart; then
          else
            echo "ERRO: Kochava ID Inválido""
            exit 1
          fi

          if grep -q "ca-app-pub-8419654969814276~6369933191" android/app/src/main/AndroidManifest.xml; then
          else
            echo "ERRO: AdMob ID Inválido."
            exit 1
          fi

      - name: Criando Tag
        run: |
          FLUTTER_VERSION_CODE=$(echo $NEW_VERSION | awk -F. '{print $1$2$3}')

          # Atualize o versionCode
          sed -i "s/versionCode .*/versionCode $FLUTTER_VERSION_CODE/" android/app/build.gradle
          # Atualize o versionName
          sed -i "s/versionName \".*\"/versionName \"$NEW_VERSION\"/" android/app/build.gradle

          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "paulo@ldcapps.com"
          git add android/app/build.gradle
          git commit -m "Release $NEW_VERSION"
          git tag $NEW_VERSION
          git push origin $NEW_VERSION