name: Release Checker

on:
  push:
    branches:
      - main

jobs:
  release_checker:
    env:
      ADMOB: ${{ secrets.ADMOB }}
      BUNDLE: ${{ secrets.BUNDLE }}
      FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
      FACEBOOK_CLIENT_TOKEN: ${{ secrets.FACEBOOK_CLIENT_TOKEN }}
      KOCHAVA: ${{ secrets.KOCHAVA }}
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verificando versão
        run: |
          git log -n 2 --pretty=format:"%h" > commits.txt
          commit_array=($(cat commits.txt))

          old_version=$(git show ${commit_array[1]}:pubspec.yaml | grep -o "version: [0-9.]*")
          new_version=$(git show ${commit_array[0]}:pubspec.yaml | grep -o "version: [0-9.]*")

          if [ "$old_version" = "$new_version" ]; then
            echo "A versão do pubspec.yaml não foi alterada. Interrompendo o script."
            exit 0
          else
            echo "A versão do pubspec.yaml mudou de $old_version para $new_version. Continuando o script."
          fi

      - name: Verificando ID's
        run: |
          applicationId=$(grep "applicationId" android/app/build.gradle | awk '{print $2}' | tr -d '"')
          if [ "$applicationId" == "$BUNDLE" ]; then
            echo "applicationId está configurado corretamente."
          else
            echo "ERRO: applicationId não está configurado corretamente."
            exit 1
          fi

          facebookAppId=$(grep '<string name="facebook_app_id">' android/app/src/main/res/values/strings.xml | awk -F'>' '{print $2}' | awk -F'<' '{print $1}')
          if [ "$facebookAppId" == "$FACEBOOK_APP_ID" ]; then
            echo "facebook_app_id está configurado corretamente."
          else
            echo "ERRO: facebook_app_id não está configurado corretamente."
            exit 1
          fi

          facebookClientToken=$(grep '<string name="facebook_client_token">' android/app/src/main/res/values/strings.xml | awk -F'>' '{print $2}' | awk -F'<' '{print $1}')
          if [ "$facebookClientToken" == "$FACEBOOK_CLIENT_TOKEN" ]; then
            echo "facebook_client_token está configurado corretamente."
          else
            echo "ERRO: facebook_client_token não está configurado corretamente."
            exit 1
          fi

          if grep -q "KochavaTracker.instance.registerAndroidAppGuid(\"$KOCHAVA\");" lib/app/core/services/log_manager_service.dart; then
            echo "A linha de código em log_manager_service.dart está configurada corretamente."
          else
            echo "ERRO: A linha de código em log_manager_service.dart não está configurada corretamente."
            exit 1
          fi

          if grep -q "$ADMOB" android/app/src/main/AndroidManifest.xml; then
            echo "Metadata no AndroidManifest.xml está configurada corretamente."
          else
            echo "ERRO: Metadata no AndroidManifest.xml não está configurada corretamente."
            exit 1
          fi

      - name: Criando Tag
        run: |
          FLUTTER_VERSION_CODE=$(echo $NEW_VERSION | awk -F. '{print $1$2$3}')

          # Atualize o versionCode
          sed -i "s/versionCode .*/versionCode $FLUTTER_VERSION_CODE/" android/app/build.gradle
          # Atualize o versionName
          sed -i "s/versionName \".*\"/versionName \"$NEW_VERSION\"/" android/app/build.gradle

          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "paulo@ldcapps.com"
          git add android/app/build.gradle
          git commit -m "Release $NEW_VERSION"
          git tag $NEW_VERSION
          git push origin $NEW_VERSION